"""
Django settings for MiRenalApp project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from decouple import config
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

#Seguridad
# Modificación N4: Quitar el valor por defecto inseguro para forzar que falle si no hay .env
SECRET_KEY = config('SECRET_KEY')

# Modificación 4: Por seguridad, el valor por defecto si no se encuentra la variable debe ser False
DEBUG = config('DEBUG', default=False, cast=bool)

# Modificación 5: Leer la lista de hosts desde el archivo .env separada por comas
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

# Aplicaciones
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.pacientes',
    'apps.citas',
    'apps.blog',
    'apps.usuarios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MiRenalApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MiRenalApp.wsgi.application'

# Base de datos (PostgreSQL con Docker)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config(
            'DB_PORT',
            default=5432,
            cast=int
        ),
    }
}

# Fuerza el dominio para que los enlaces en los correos sean clickeables y válidos
SITE_NAME = config(
    'SITE_NAME',
    default='Kidnely Health'
)

# Tiempo máximo de espera para correo
EMAIL_TIMEOUT = config(
    'EMAIL_TIMEOUT',
    default=30,
    cast=int
)

# Validación de contraseñas
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internacionalización
LANGUAGE_CODE = 'es'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# ARCHIVOS ESTÁTICOS Y MULTIMEDIA
# ==============================================================================

# 1. La URL con la que el navegador pedirá los archivos
STATIC_URL = '/static/'

# 2. Dónde recolecta Docker los archivos en producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 3. CRUCIAL: Indicamos a Django dónde buscar la carpeta verde 'static'
STATICFILES_DIRS = [
    BASE_DIR / 'MiRenalApp' / 'static',
]

# 4. Configuración para el contenido subido por usuarios (Imágenes de pacientes/artículos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==============================================================================
# AUTENTICACIÓN Y REDIRECCIONES
# ==============================================================================
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# ==============================================================================
# CONFIGURACIÓN DE CORREO ELECTRÓNICO
# ==============================================================================
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.smtp.EmailBackend'
)

EMAIL_HOST = config(
    'EMAIL_HOST',
    default='smtp.gmail.com'
)

EMAIL_PORT = config(
    'EMAIL_PORT',
    default=587,
    cast=int
)

EMAIL_USE_TLS = config(
    'EMAIL_USE_TLS',
    default=True,
    cast=bool
)

# Permitir arranque aunque estén vacías
EMAIL_HOST_USER = config(
    'EMAIL_HOST_USER',
    default=''
)

EMAIL_HOST_PASSWORD = config(
    'EMAIL_HOST_PASSWORD',
    default=''
)

DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default=EMAIL_HOST_USER
)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Orígenes confiables para protección CSRF
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:8000,http://127.0.0.1:8000',
    cast=lambda v: [s.strip() for s in v.split(',')]
)