# Generated by Django 5.1.4 on 2026-03-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_esta_bloqueado_alter_perfil_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, default='perfiles/default.png', null=True, upload_to='perfiles/'),
        ),
    ]
