# Generated by Django 5.1.4 on 2026-03-16 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_perfil_id_alter_perfil_imagen_opinion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='opiniones_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opinion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='opiniones_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
